FROM node:20-alpine
WORKDIR /app

# Copia apenas package.json e package-lock.json
COPY package*.json ./
RUN npm install

# Copia todo o código
COPY . .

# Expondo a porta do React
EXPOSE 3000

# Rodando em modo desenvolvimento (hot-reload)
CMD ["npm", "start"]