FROM node:20
WORKDIR /app

# Copia apenas package.json e package-lock.json
COPY package*.json ./

# Instala as dependências do zero
RUN npm install --legacy-peer-deps --no-optional


# Copia todo o código
COPY . .

# Expondo a porta do React
EXPOSE 3000

# Rodando em modo desenvolvimento (hot-reload)
CMD ["npm", "run", "dev"]
