name: Merge Dev → Main e Deploy

on:
  workflow_run:
    workflows: ["FrontEnd CI"] # nome exato do seu workflow que roda na dev
    types:
      - completed

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Merge automático da dev para main
      - name: Merge dev into main
        uses: devops-infra/action-pull-request@v0.3.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: dev
          target_branch: main
          merge_method: merge  # pode ser merge, squash ou rebase

      # Deploy (exemplo DigitalOcean App ou VPS via SSH)
      # - name: Deploy via SSH
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       cd /caminho/do/projeto
      #       git pull origin main
      #       npm install --production
      #       npm run build
      #       pm2 restart all # ou o comando que você usa pra rodar seu app
