name: FrontEnd CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Lint
        run: |
          if npm run | grep -q "lint"; then npm run lint; else echo "Sem script lint, pulando"; fi

      - name: Run tests
        env:
          CI: true
        run: |
          if npm run | grep -q "test"; then npm run test -- --watch=false || npm run test -- --run; else echo "Sem script test, pulando"; fi
        
      - name: Build
        run: |
          if npm run | grep -q "build"; then npm run build else echo "Sem script build, pulando"; fi
  
  docker-security:
    runs-on: ubuntu-latest
    needs: test #only run if pass all tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t frontend:test .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: frontend:test
          severity: HIGH,CRITICAL
          format: table
          exit-code: 1 #fail with high vulnerability

      - name: Run Docker Bench Security
        run: |
          docker run --rm --net host --pid host --userns host \
            --cap-add audit_control \
            -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
            -v /var/lib:/var/lib \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v /usr/lib/systemd:/usr/lib/systemd \
            -v /etc:/etc \
            docker/docker-bench-security